// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmcabwxxlmrignirgjiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtY2Fid3h4bG1yaWduaXJnaml3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4Mjg1ODMsImV4cCI6MjA2MTQwNDU4M30.flpcMhqjMOuhR65Rr_Fb8eVUMEwZQ_bPoWYlV7tYQRE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);